name: Build website

on:
  push:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Archive production build
        run: |
          tar -czf website.tar.gz ./dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Website Release ${{ github.run_number }}
          tag_name: v${{ github.run_number }}
          files: website.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
